package kz.edu.web;

import org.h2.jdbcx.JdbcDataSource;
import org.postgresql.ds.PGSimpleDataSource;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Создание DataSource и начальной схемы.
 * По умолчанию — встроенная H2 (в памяти). Если задана переменная окружения DB_URL
 * (например, jdbc:postgresql://localhost:5432/university), используется PostgreSQL;
 * логин и пароль берутся из DB_USER и DB_PASSWORD.
 */
final class Database {

    private Database() {
    }

    static DataSource createDataSource() {
        String url = System.getenv("DB_URL");

        if (url != null && url.startsWith("jdbc:postgresql:")) {
            PGSimpleDataSource ds = new PGSimpleDataSource();
            ds.setUrl(url);
            ds.setUser(System.getenv("DB_USER"));
            ds.setPassword(System.getenv("DB_PASSWORD"));
            return ds;
        }

        JdbcDataSource ds = new JdbcDataSource();
        ds.setURL("jdbc:h2:mem:shop;DB_CLOSE_DELAY=-1");
        ds.setUser("sa");
        return ds;
    }

    /** Создаёт таблицу orders и, если она пуста, добавляет тестовые данные. */
    static void init(DataSource dataSource) throws SQLException {
        try (Connection connection = dataSource.getConnection()) {
            boolean postgres = connection.getMetaData().getURL().startsWith("jdbc:postgresql:");
            String idType = postgres ? "BIGSERIAL PRIMARY KEY" : "BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY";

            try (Statement st = connection.createStatement()) {
                st.executeUpdate("CREATE TABLE IF NOT EXISTS orders ("
                        + "id " + idType + ", "
                        + "customer VARCHAR(100) NOT NULL, "
                        + "item VARCHAR(100) NOT NULL, "
                        + "quantity INTEGER NOT NULL, "
                        + "amount INTEGER NOT NULL, "
                        + "status VARCHAR(20) NOT NULL)");
            }

            try (PreparedStatement count = connection.prepareStatement("SELECT COUNT(*) FROM orders");
                 ResultSet rs = count.executeQuery()) {
                rs.next();
                if (rs.getLong(1) > 0) {
                    return;
                }
            }

            String insert = "INSERT INTO orders (customer, item, quantity, amount, status) VALUES (?, ?, ?, ?, ?)";
            Object[][] seed = {
                    {"Иван Иванов", "Ноутбук", 1, 450_000, "PAID"},
                    {"Алия Садыкова", "Мышь беспроводная", 2, 12_000, "NEW"},
                    {"Петр Петров", "Монитор 27\"", 2, 240_000, "SHIPPED"},
                    {"Динара Ержанова", "Клавиатура", 1, 18_000, "CANCELLED"},
            };
            try (PreparedStatement ps = connection.prepareStatement(insert)) {
                for (Object[] row : seed) {
                    ps.setString(1, (String) row[0]);
                    ps.setString(2, (String) row[1]);
                    ps.setInt(3, (Integer) row[2]);
                    ps.setInt(4, (Integer) row[3]);
                    ps.setString(5, (String) row[4]);
                    ps.executeUpdate();
                }
            }
        }
    }
}
